### ISSUE TITLE
Upgrade java driver to 4.3.x

### ISSUE THREAD

**Issue by denniskline** [instaclustr/cassandra-java-driver-kerberos#2]
Datastax's 4.x java driver has many breaking changes.  

- https://github.com/datastax/java-driver/tree/4.x/changelog

- https://docs.datastax.com/en/developer/java-driver/4.3/upgrade_guide/

If Instaclustr would like, I can contribute an update to make this driver compatible with 4.3.x?

**Comment by slater-ben** [comment]
Hi Dennis, we'd be very happy to review a PR. Thanks for your interest and contribution!

**Comment by smiklosovic** [comment]
Hi @denniskline , I ve merged it but I realized that the documentation and javadoc is not aligned with Cassandra driver version 4.x. Could you please make a PR and update it as well? Once done, I will cut a new release of 1.1.0 to Maven Central.

Thank you for your contribution.

**Comment by denniskline** [comment]
Thanks @smiklosovic!  I'll submit another PR with an update to the docs.  

As a potentially new feature ... what are your thoughts on allowing for a custom hostname resolver?  Without an override, it could default to how it is defined now but users with vips (or something else odd) could add some custom logic to specify the hostname.  If you think this would be helpful, I can submit another PR with that change as well?

Thanks!
-Dennis

**Comment by smiklosovic** [comment]
@denniskline sure thing, go ahead and we will merge gladly, as long as it preserves default behaviour with the option to override it with something custom.
