### ISSUE TITLE
Add support for file-based configuration

### ISSUE THREAD

**Issue by zegelin** [instaclustr/cassandra-java-driver-kerberos#6]
The Java driver v4 uses Typesafe config to permit file-based configuration.

Currently this plugin doesn't support this.

See the docs for more info: https://github.com/datastax/java-driver/tree/4.x/manual/core/authentication#custom

**Comment by smiklosovic** [comment]
Noticed. This will be nice feature indeed. Let's give me couple days here.

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-java-driver-kerberos/pull/7

**Comment by smiklosovic** [comment]
Done in version 3.0.0
